[book]
authors = ["SorahISA"]
language = "en"
multilingual = false
src = "src"
title = "SorahISA's Contest Logs"

[preprocessor.katex]
after = ["links"]
macros = "./settings/katex-macros.txt"

[output.html]
mathjax-support = true
no-section-label = true
smart-punctuation = true
additional-css = ["settings/log.css", "settings/custom.css"]

[output.html.fold]
enable = true
level = 2
